"""test

Revision ID: 2577f4faf338
Revises: 
Create Date: 2023-04-18 16:14:31.480659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2577f4faf338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('holes',
    sa.Column('hole_number', sa.Integer(), nullable=True),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_holes_course_id_courses')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_players_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_rounds_course_id_courses')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecards',
    sa.Column('round_type', sa.String(), nullable=True),
    sa.Column('score_1', sa.Integer(), nullable=True),
    sa.Column('score_2', sa.Integer(), nullable=True),
    sa.Column('score_3', sa.Integer(), nullable=True),
    sa.Column('score_4', sa.Integer(), nullable=True),
    sa.Column('score_5', sa.Integer(), nullable=True),
    sa.Column('score_6', sa.Integer(), nullable=True),
    sa.Column('score_7', sa.Integer(), nullable=True),
    sa.Column('score_8', sa.Integer(), nullable=True),
    sa.Column('score_9', sa.Integer(), nullable=True),
    sa.Column('score_10', sa.Integer(), nullable=True),
    sa.Column('score_11', sa.Integer(), nullable=True),
    sa.Column('score_12', sa.Integer(), nullable=True),
    sa.Column('score_13', sa.Integer(), nullable=True),
    sa.Column('score_14', sa.Integer(), nullable=True),
    sa.Column('score_15', sa.Integer(), nullable=True),
    sa.Column('score_16', sa.Integer(), nullable=True),
    sa.Column('score_17', sa.Integer(), nullable=True),
    sa.Column('score_18', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_scorecards_player_id_players')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_scorecards_round_id_rounds')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_scorecards_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecards')
    op.drop_table('rounds')
    op.drop_table('players')
    op.drop_table('holes')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_table('courses')
    # ### end Alembic commands ###
